### ISSUE TITLE
[BUG][SLIM6] Cant add apps to homescreen from App Drawer

### ISSUE THREAD

**Issue by skinzor** [SlimRoms/packages_apps_SlimLauncher#3]
Hi there!
I'm using Slim6 and it seems that apps can't be added on homescreen from App Drawer. When the drawer is paged, long pressing an app icon does nothing. But in vertical drawer it works fine.

Is this issue present on Slim7 too? If not, can you give me a tip about how can I fix this on Slim6?

Here is a logcat, took with CatLog app:  https://www.mediafire.com/download/5ln1r14iwrp5ar1 .

Meanwhile, I'll do a search myself.

**Comment by YAJATapps** [comment]
This will fix that issue
https://github.com/Team-OctOS/platform_packages_apps_Launcher3/commit/e09120b808feca52f73e4257e12d34773c6c5900

**Comment by skinzor** [comment]
@YAJATapps 

Thank you alot!

**Comment by YAJATapps** [comment]
Slim 7 currently don't have paged drawer.

**Comment by skinzor** [comment]
Im closing this issue as it has been solved!
